
const ChainsActionsConstants = {
    LOAD_CHAINS_ACTION :"LOAD_CHAINS_ACTION",
    LOAD_CHAINS_ACTION_SUCCESS :"LOAD_CHAINS_ACTION_SUCCESS",
    LOAD_CHAINS_ACTION_FAILURE :"LOAD_CHAINS_ACTION_FAILURE",
    REVIEW_CHAIN_ACTION: 'REVIEW_CHAIN_ACTION',
    SORT_REVIEW_ACTION: 'SORT_REVIEW_ACTION',
    DELETE_REVIEW_ACTION: 'DELETE_REVIEW_ACTION',
    EDIT_REVIEW_ACTION: 'EDIT_REVIEW_ACTION',
    EDIT_REVIEW_ACTION_SUCCESS: 'EDIT_REVIEW_ACTION_SUCCESS',
    EDIT_REVIEW_ACTION_FAILURE: 'EDIT_REVIEW_ACTION_FAILURE',
    REVIEW_ACTION_SUCCESS:'REVIEW_ACTION_SUCCESS',
    REVIEW_ACTION_FAILURE:'REVIEW_ACTION_FAILURE',
    DELETE_ACTION_SUCCESS:'DELETE_ACTION_SUCCESS',
    DELET_ACTION_FAILURE:'DELETE_ACTION_FAILURE',
    UPADTE_TO_REVIEW:'UPADTE_TO_REVIEW',
    SET_ACTIVE_IMAGE:'SET_ACTIVE_IMAGE',
    UNSET_ACTIVE_IMAGE:'UNSET_ACTIVE_IMAGE'

}

export {ChainsActionsConstants}