const EditActions = {
    UPDATE_VALUE: "EDIT_UPDATE_VALUE",
    UPDATE_VALUE_SUCCESS: "UPDATE_VALUE_SUCCESS",
    UPDATE_VALUE_FAILED: "UPDATE_VALUE_FAILED",
    UPDATE_LOCATION: "UPDATE_LOCATION",
    SAVE: "SAVE"
}

export default EditActions;