
const RegisterActionsConstants = {
  REGISTER_USER: "REGISTER_USER",
  REGISTER_USER_ERROR: "REGISTER_USER_ERROR",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  LOGIN_USER: "LOGIN_USER", 
  LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
  LOAD_USERS: "LOAD_USERS", 
  LOAD_USERS_SUCCESS: "LOAD_USERS_SUCCESS",
  LOAD_USERS_FAILED: "LOAD_USERS_FAILED",
  UPDATE_USERNAME: "UPDATE_USERNAME",
  UPDATE_LOCATION: "UPDATE_LOCATION"
};

export { RegisterActionsConstants };