let LoginConstans = {
    LOGIN_USER: "LOGIN_USER",
    LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    SIGN_OUT_USER:"SIGN_OUT_USER",
    UPDATE_VALUE: "UPDATE_VALUE",
    LOGIN_WITH_FB: "LOGIN_WITH_FB"
};

export default LoginConstans;