
const AdvanceSearchConstants = {
    UPDATE_VALUE: "ADVANCE_UPDATE_VALUE",
    SEARCH: "ADVANCE_SEARCH",
    SEARCH_ERROR: "ADVANCE_SEARCH_ERROR",
    SEARCH_SUCCESS: "ADVANCE_SEARCH_SUCCESS",
    ON_SUGGEST_SELECT: "ADVANCE_ON_SUGGEST_SELECT"
}

export default AdvanceSearchConstants;